version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  geth:
    build: ../geth
    command: '--networkid 1234567890 --datadir "/root/.ethereum/devchain" --port "30303" --rpc --rpcport "8545" --rpccorsdomain "*" --rpcaddr="0.0.0.0" --rpcapi "admin,db,eth,miner,net,web3,personal,txpool" --nodiscover --mine --minerthreads=2 --etherbase 0'
    ports:
      - "8544:8544"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - geth:/root/.ethereum
  bridge:
    build: ../bridge
    command: /bridge -port 8555
    ports:
      - "8555:8555"
  web:
    build: ../web
    command: bundle exec puma
    volumes:
      - ../web:/web
    ports:
      - "3000:3000"
    environment:
      BRIDGE_HOST: bridge
      POSTGRES_HOST: db
    depends_on:
      - db
      - geth
      - bridge

volumes:
  postgresql-data:
    driver: local
  geth:
    driver: local
